"use client";
import {useMemo,useState} from "react";

type Question={category:string,image?:string,q:string,options:string[],answer:number,tip:string};
const questions:Question[]=[
 {category:"事故快报",image:"/scenes/foreign-matter.svg",q:"你是第一发现人。此时最正确的第一步是什么？",options:["继续生产，稍后观察","暂停相关操作，保护现场并立即汇报主管和QA","自行丢弃异物，不做记录","下班后再告诉同事"],answer:1,tip:"先遏制风险、保护证据，再按流程及时升级汇报。"},
 {category:"信息完整性",image:"/scenes/foreign-matter.svg",q:"针对该现场，哪组信息最适合作为初始快报？",options:["现场有问题，请来看看","10:20包装线发现批号A01成品中有黑色颗粒，生产已暂停，相关产品已隔离","操作员可能粗心了","拍照后不需要文字说明"],answer:1,tip:"快报应说明时间、地点、事件、涉及对象、影响范围和即时措施。"},
 {category:"过敏原",image:"/scenes/allergen-leak.svg",q:"看到这个现场，优先控制措施是什么？",options:["用普通扫把快速清理","隔离区域和相关物料，防止扩散并立即汇报","把破损袋移到角落","等待下一班处理"],answer:1,tip:"过敏原异常应优先阻止扩散和交叉污染。"},
 {category:"过敏原",image:"/scenes/allergen-leak.svg",q:"汇报该事件时，哪项信息最关键？",options:["包装袋颜色","物料名称、批号、泄漏位置、影响区域和已采取措施","当天气温","清洁人员姓名"],answer:1,tip:"物料身份、影响范围和控制状态决定后续风险评估。"},
 {category:"标签与发货",image:"/scenes/wrong-label.svg",q:"货物尚未出厂，正确处置是什么？",options:["立即停止发货并隔离相关产品","先发货再通知客户","只更换外箱标签","删除发货记录"],answer:0,tip:"先阻止错误产品流向客户，再核查标签、实物及受影响范围。"},
 {category:"设备异常",image:"/scenes/temperature.svg",q:"仪表显示异常且可能影响产品，第一步应怎么做？",options:["自行调整记录使其符合标准","暂停相关操作，核实仪表状态并汇报","继续运行直到检测不合格","只通知维修，不说明产品影响"],answer:1,tip:"设备异常与产品风险必须同步控制和评估。"},
 {category:"设备异常",image:"/scenes/temperature.svg",q:"快报中必须补充哪组信息？",options:["设备编号、异常时段、标准值、实际值及可能涉及批次","设备购买价格","维修人员年龄","控制屏颜色"],answer:0,tip:"明确偏差程度和影响时间窗，才能界定受影响批次。"},
 {category:"虫害",image:"/scenes/pest.svg",q:"发现虫害痕迹后，哪种做法正确？",options:["自行清除后不留记录","拍照记录位置，避免扰动，立即通知主管和虫害管理责任人","喷洒不明杀虫剂","等再次发现活虫再汇报"],answer:1,tip:"应保留证据、明确位置并按虫害管理流程升级。"},
 {category:"客观描述",q:"事件汇报中，哪种描述最客观？",options:["某员工粗心导致事故","现场管理一直很差","10:20在包装线发现批号A01产品中有黑色颗粒","我感觉问题应该不大"],answer:2,tip:"描述事实，不主观归责，不使用模糊判断。"},
 {category:"即时措施",q:"以下哪项属于有效的即时控制措施？",options:["删除异常记录","隔离受影响产品并暂停相关操作","要求员工不要讨论","修改检测结果"],answer:1,tip:"即时措施应阻止风险继续扩大，并保留调查条件。"},
 {category:"汇报意识",q:"暂时无法判断事件严重程度，应该怎么做？",options:["不汇报","及时汇报，由相关人员共同评估风险","等结果出来后再说","自行判定为低风险"],answer:1,tip:"不确定不等于不报告，及时升级可避免低估风险。"},
 {category:"闭环确认",q:"同事也看到了异常，你还需要汇报吗？",options:["不需要，默认同事会处理","需要，除非已确认事件已按流程报告并受控","造成损失后再汇报","只告诉熟悉的同事"],answer:1,tip:"不能假设别人已完成汇报，应确认责任人、控制状态和闭环。"},
 {category:"照片证据",q:"事件照片怎样拍摄最有助于调查？",options:["只拍看不清位置的远景","拍摄现场全景、异常近照和批号或设备标识","美化照片后提交","只拍人员，不拍异常"],answer:1,tip:"全景用于定位，近景用于识别问题，标识用于追溯。"}
];
const path=[0,1,2,3,4,5,11,10,9,8,7,6,12,13,14,15,16,17,23,22,21,20,19,18];
const special:Record<number,string>={4:"好运",8:"QA",12:"风险",16:"快报",20:"加速"};
export default function Page(){
 const [position,setPosition]=useState(0),[dice,setDice]=useState<number|null>(null),[rolling,setRolling]=useState(false),[question,setQuestion]=useState<Question|null>(null),[selected,setSelected]=useState<number|null>(null),[locked,setLocked]=useState(false),[correct,setCorrect]=useState(0),[wrong,setWrong]=useState(0),[message,setMessage]=useState("掷骰子，开启事故快报挑战"),[finished,setFinished]=useState(false),[used,setUsed]=useState<number[]>([]);
 const cells=useMemo(()=>Array.from({length:24},(_,i)=>i),[]),progress=Math.round(position/(path.length-1)*100);
 function pick(){const pool=questions.map((_,i)=>i).filter(i=>!used.includes(i));const candidates=pool.length?pool:questions.map((_,i)=>i);const index=candidates[Math.floor(Math.random()*candidates.length)];setUsed(pool.length?[...used,index]:[index]);return questions[index]}
 function roll(){if(rolling||question||finished)return;setRolling(true);setMessage("骰子滚动中...");let t=0;const id=setInterval(()=>{setDice(Math.ceil(Math.random()*6));if(++t>=9){clearInterval(id);const v=Math.ceil(Math.random()*6);setDice(v);setRolling(false);setQuestion(pick());setMessage(`掷出 ${v} 点，答对才能前进`)}},80)}
 function choose(i:number){if(locked||!question||dice===null)return;setSelected(i);setLocked(true);if(i===question.answer){setCorrect(v=>v+1);setMessage("回答正确，棋子前进！");setTimeout(()=>{const n=Math.min(position+dice,path.length-1);setPosition(n);setQuestion(null);setLocked(false);setSelected(null);if(n===path.length-1)setFinished(true)},900)}else{setWrong(v=>v+1);setMessage("回答错误，留在原地");setTimeout(()=>{setQuestion(null);setLocked(false);setSelected(null)},1500)}}
 function reset(){setPosition(0);setDice(null);setRolling(false);setQuestion(null);setSelected(null);setLocked(false);setCorrect(0);setWrong(0);setMessage("掷骰子，开启事故快报挑战");setFinished(false);setUsed([])}
 return <main className="app"><div className="wrap"><header className="header"><div><div className="eyebrow">SHE & Q DAY · 单人3分钟挑战</div><h1 className="title">质量大富翁 <span className="cyan">·事故快报版</span></h1><div className="sub">掷骰子 → 查看现场 → 判断与汇报 → 答对前进，答错留在原地</div></div><button className="btn secondary" onClick={reset}>↻ 重新开始</button></header><div className="layout"><section className="card board">{cells.map(v=>{const step=path.indexOf(v),active=step===position,passed=step<position,label=special[step];return <div key={v} className={`cell ${active?"active":""} ${passed?"passed":""} ${label?"special":""}`}>{step===0?"🚨":step===path.length-1?"🏁":label?<><span>⭐</span><span className="specialLabel">{label}</span></>:step+1}{active&&<span className="pawn">♟</span>}</div>})}</section><aside className="side"><section className="card diceCard"><div className="cyan">当前骰子</div><div className={`dice ${rolling?"rolling":""}`}>{dice||"?"}</div><button className="btn full" onClick={roll} disabled={rolling||!!question||finished}>🎲 {rolling?"滚动中":"掷骰子"}</button><p className="message">{message}</p></section><section className="card stats"><div className="row"><span>通关进度</span><b className="cyan">{progress}%</b></div><div className="progressTrack"><div className="progressBar" style={{width:`${progress}%`}}/></div><div className="statgrid"><div className="stat"><div className="num good">{correct}</div><small>答对</small></div><div className="stat"><div className="num bad">{wrong}</div><small>答错</small></div></div><p className="tiny">题库 {questions.length} 题 · 本轮优先不重复</p></section></aside></div></div>{question&&<div className="overlay"><section className="card modal"><div className="modalHead"><span>⚡ {question.category}</span><span className="pill">答对前进 {dice} 格</span></div>{question.image&&<div className="scene"><img src={question.image} alt="模拟质量异常现场"/></div>}<h2 className="question">{question.q}</h2><div className="options">{question.options.map((o,i)=>{const cls=locked&&i===question.answer?"correct":locked&&selected===i&&i!==question.answer?"wrong":"";return <button disabled={locked} className={`option ${cls}`} key={o} onClick={()=>choose(i)}><span className="letter">{String.fromCharCode(65+i)}</span>{o}</button>})}</div>{locked&&<div className="tip"><b className="cyan">快报要点：</b>{question.tip}</div>}</section></div>}{finished&&<div className="overlay"><section className="card modal finish"><div className="trophy">🏆</div><h2>事故成功受控！</h2><p className="sub">你已获得“金牌事故快报员”称号</p><div className="finishGrid"><div className="stat"><div className="num good">{correct}</div>正确题数</div><div className="stat"><div className="num bad">{wrong}</div>错误题数</div></div><button className="btn full" onClick={reset}>再玩一次</button></section></div>}</main>
}
